FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o publisher ./cmd/publisher_worker

FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/publisher ./publisher

# config.yaml монтируется из docker-compose, см. Dockerfile сервиса.

ENTRYPOINT ["./publisher"]
