// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package schema

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Platform.
const (
	Instagram Platform = "instagram"
	Threads   Platform = "threads"
	Tiktok    Platform = "tiktok"
	Youtube   Platform = "youtube"
)

// Valid indicates whether the value is a known member of the Platform enum.
func (e Platform) Valid() bool {
	switch e {
	case Instagram:
		return true
	case Threads:
		return true
	case Tiktok:
		return true
	case Youtube:
		return true
	default:
		return false
	}
}

// Defines values for PostKind.
const (
	Text  PostKind = "text"
	Video PostKind = "video"
)

// Valid indicates whether the value is a known member of the PostKind enum.
func (e PostKind) Valid() bool {
	switch e {
	case Text:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for PostStatus.
const (
	PostStatusDraft              PostStatus = "draft"
	PostStatusFailed             PostStatus = "failed"
	PostStatusPartiallyPublished PostStatus = "partially_published"
	PostStatusPublished          PostStatus = "published"
	PostStatusPublishing         PostStatus = "publishing"
	PostStatusScheduled          PostStatus = "scheduled"
)

// Valid indicates whether the value is a known member of the PostStatus enum.
func (e PostStatus) Valid() bool {
	switch e {
	case PostStatusDraft:
		return true
	case PostStatusFailed:
		return true
	case PostStatusPartiallyPublished:
		return true
	case PostStatusPublished:
		return true
	case PostStatusPublishing:
		return true
	case PostStatusScheduled:
		return true
	default:
		return false
	}
}

// Defines values for TargetStatus.
const (
	TargetStatusFailed     TargetStatus = "failed"
	TargetStatusPending    TargetStatus = "pending"
	TargetStatusPublished  TargetStatus = "published"
	TargetStatusPublishing TargetStatus = "publishing"
)

// Valid indicates whether the value is a known member of the TargetStatus enum.
func (e TargetStatus) Valid() bool {
	switch e {
	case TargetStatusFailed:
		return true
	case TargetStatusPending:
		return true
	case TargetStatusPublished:
		return true
	case TargetStatusPublishing:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Id       string     `json:"id"`
	IsActive bool       `json:"is_active"`
	Platform Platform   `json:"platform"`
	SyncedAt *time.Time `json:"synced_at,omitempty"`
	Username *string    `json:"username,omitempty"`
}

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	Content     *string    `json:"content,omitempty"`
	Kind        PostKind   `json:"kind"`
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`
	Targets     []struct {
		Caption  *string  `json:"caption,omitempty"`
		Platform Platform `json:"platform"`
	} `json:"targets"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Media defines model for Media.
type Media struct {
	FileName  string  `json:"file_name"`
	Id        string  `json:"id"`
	MimeType  *string `json:"mime_type,omitempty"`
	PublicUrl string  `json:"public_url"`
	SizeBytes *int64  `json:"size_bytes,omitempty"`
}

// Platform defines model for Platform.
type Platform string

// Post defines model for Post.
type Post struct {
	Content     *string    `json:"content,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Id          string     `json:"id"`
	Kind        PostKind   `json:"kind"`
	Media       *[]Media   `json:"media,omitempty"`
	PublishedAt *time.Time `json:"published_at,omitempty"`
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`
	Status      PostStatus `json:"status"`
	Targets     []Target   `json:"targets"`
}

// PostKind defines model for PostKind.
type PostKind string

// PostStatus defines model for PostStatus.
type PostStatus string

// Target defines model for Target.
type Target struct {
	Caption        *string      `json:"caption,omitempty"`
	ErrorMessage   *string      `json:"error_message,omitempty"`
	ExternalPostId *string      `json:"external_post_id,omitempty"`
	ExternalUrl    *string      `json:"external_url,omitempty"`
	Id             string       `json:"id"`
	Platform       Platform     `json:"platform"`
	Status         TargetStatus `json:"status"`
}

// TargetStatus defines model for TargetStatus.
type TargetStatus string

// GetConnectURLParams defines parameters for GetConnectURL.
type GetConnectURLParams struct {
	Platform    Platform `form:"platform" json:"platform"`
	RedirectUrl *string  `form:"redirect_url,omitempty" json:"redirect_url,omitempty"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// ListPostsParams defines parameters for ListPosts.
type ListPostsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// UploadVideoMultipartBody defines parameters for UploadVideo.
type UploadVideoMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = CreatePostRequest

// UploadVideoMultipartRequestBody defines body for UploadVideo for multipart/form-data ContentType.
type UploadVideoMultipartRequestBody UploadVideoMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List accounts
	// (GET /v1/accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request)
	// Get connect url
	// (GET /v1/accounts/connect_url)
	GetConnectURL(w http.ResponseWriter, r *http.Request, params GetConnectURLParams)
	// Sync accounts
	// (POST /v1/accounts/sync)
	SyncAccounts(w http.ResponseWriter, r *http.Request)
	// Login
	// (POST /v1/login)
	Login(w http.ResponseWriter, r *http.Request)
	// List posts
	// (GET /v1/posts)
	ListPosts(w http.ResponseWriter, r *http.Request, params ListPostsParams)
	// Create post
	// (POST /v1/posts)
	CreatePost(w http.ResponseWriter, r *http.Request)
	// Delete post
	// (DELETE /v1/posts/{post_id})
	DeletePost(w http.ResponseWriter, r *http.Request, postId string)
	// Get post
	// (GET /v1/posts/{post_id})
	GetPost(w http.ResponseWriter, r *http.Request, postId string)
	// Upload video
	// (POST /v1/posts/{post_id}/media)
	UploadVideo(w http.ResponseWriter, r *http.Request, postId string)
	// Publish post
	// (POST /v1/posts/{post_id}/publish)
	PublishPost(w http.ResponseWriter, r *http.Request, postId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List accounts
// (GET /v1/accounts)
func (_ Unimplemented) ListAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get connect url
// (GET /v1/accounts/connect_url)
func (_ Unimplemented) GetConnectURL(w http.ResponseWriter, r *http.Request, params GetConnectURLParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sync accounts
// (POST /v1/accounts/sync)
func (_ Unimplemented) SyncAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login
// (POST /v1/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List posts
// (GET /v1/posts)
func (_ Unimplemented) ListPosts(w http.ResponseWriter, r *http.Request, params ListPostsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create post
// (POST /v1/posts)
func (_ Unimplemented) CreatePost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete post
// (DELETE /v1/posts/{post_id})
func (_ Unimplemented) DeletePost(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get post
// (GET /v1/posts/{post_id})
func (_ Unimplemented) GetPost(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload video
// (POST /v1/posts/{post_id}/media)
func (_ Unimplemented) UploadVideo(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Publish post
// (POST /v1/posts/{post_id}/publish)
func (_ Unimplemented) PublishPost(w http.ResponseWriter, r *http.Request, postId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConnectURL operation middleware
func (siw *ServerInterfaceWrapper) GetConnectURL(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetConnectURLParams

	// ------------- Required query parameter "platform" -------------

	if paramValue := r.URL.Query().Get("platform"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "platform"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "platform", r.URL.Query(), &params.Platform, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platform", Err: err})
		return
	}

	// ------------- Optional query parameter "redirect_url" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "redirect_url", r.URL.Query(), &params.RedirectUrl, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_url", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConnectURL(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncAccounts operation middleware
func (siw *ServerInterfaceWrapper) SyncAccounts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPosts operation middleware
func (siw *ServerInterfaceWrapper) ListPosts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPostsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePost operation middleware
func (siw *ServerInterfaceWrapper) CreatePost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPost operation middleware
func (siw *ServerInterfaceWrapper) GetPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadVideo operation middleware
func (siw *ServerInterfaceWrapper) UploadVideo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadVideo(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishPost operation middleware
func (siw *ServerInterfaceWrapper) PublishPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", chi.URLParam(r, "post_id"), &postId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishPost(w, r, postId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/accounts", wrapper.ListAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/accounts/connect_url", wrapper.GetConnectURL)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/accounts/sync", wrapper.SyncAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/posts", wrapper.ListPosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/posts", wrapper.CreatePost)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/posts/{post_id}", wrapper.DeletePost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/posts/{post_id}", wrapper.GetPost)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/posts/{post_id}/media", wrapper.UploadVideo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/posts/{post_id}/publish", wrapper.PublishPost)
	})

	return r
}
